version: 0.0
os: windows
files:
 - source: \
   destination: C:\inetpub\wwwroot\
resources:
- repo: self
  clean: true
hooks:
  BeforeInstall:
    - location: \before_install.bat
      runas: administrator
      timeout: 900
  AfterInstall:
    - location: \after_install.bat
      runas: administrator
      timeout: 900